name: Génération de Carte à Gratter

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: "Image de fond pour la carte"
        required: true
      text:
        description: "Texte pour la carte"
        required: true
      color:
        description: "Couleur du texte"
        required: true

jobs:
  create_card:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Afficher les paramètres de création de carte
        run: |
          echo "Image URL : ${{ github.event.inputs.image_url }}"
          echo "Texte : ${{ github.event.inputs.text }}"
          echo "Couleur : ${{ github.event.inputs.color }}"

      - name: Configurer Git User
        run: |
          git config --global user.email "etienneleborgne@gmail.com"
          git config --global user.name "lumios-le-jeu"

      - name: Créer un nouveau dépôt sur GitHub
        env:
          REPO_NAME: "card-$(date +%s)"
        run: |
          echo "Nom du dépôt : $REPO_NAME"
          curl -u lumios-le-jeu:${{ secrets.GH_TOKEN }} https://api.github.com/user/repos -d "{\"name\":\"$REPO_NAME\"}"
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Cloner le modèle de carte et changer le remote
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
        run: |
          git clone https://github.com/lumios-le-jeu/carte-a-gratter-template.git $REPO_NAME
          cd $REPO_NAME
          git remote rm origin
          git remote add origin https://lumios-le-jeu:${{ secrets.GH_TOKEN }}@github.com/lumios-le-jeu/$REPO_NAME.git

      - name: Personnaliser la carte
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
        run: |
          cd $REPO_NAME
          # Exemple d'utilisation des variables pour personnaliser la carte
          sed -i "s|PLACEHOLDER_IMAGE_URL|${{ github.event.inputs.image_url }}|g" index.html
          sed -i "s|PLACEHOLDER_TEXT|${{ github.event.inputs.text }}|g" index.html
          sed -i "s|PLACEHOLDER_COLOR|${{ github.event.inputs.color }}|g" index.html
          git add .
          git commit -m "Personnalisation de la carte avec le texte et l'image de fond"
          git push -u origin main

      - name: Activer GitHub Pages
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
        run: |
          curl -u lumios-le-jeu:${{ secrets.GH_TOKEN }} -X POST \
          -H "Accept: application/vnd.github.switcheroo-preview+json" \
          https://api.github.com/repos/lumios-le-jeu/$REPO_NAME/pages/enable \
          -d '{"source":{"branch":"main","path":"/"}}'

      - name: Afficher l'URL de la carte
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
        run: |
          echo "Votre carte est disponible à l'adresse suivante :"
          echo "https://lumios-le-jeu.github.io/$REPO_NAME/"
