name: Génération de Carte à Gratter

on:
  workflow_dispatch:
    inputs:
      background_image_url:
        description: "URL de l'image de fond"
        required: true
        default: "https://raw.githubusercontent.com/lumios-le-jeu/cadeau/main/bon_lumios.jpg"
      scratch_text:
        description: "Texte pour la carte"
        required: true
        default: "Votre texte ici"
      color:
        description: "Couleur pour le texte"
        required: true
        default: "#FF0000"

jobs:
  create_card:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du générateur
      uses: actions/checkout@v3

    - name: Configurer l'utilisateur Git
      run: |
        git config --global user.name "lumios-le-jeu"
        git config --global user.email "etienneleborgne@gmail.com"

    - name: Générer un nom de dépôt unique pour le résultat
      id: result_repo
      run: echo "repo_name=carte-a-gratter-resultat-$(date +%s)" >> $GITHUB_ENV

    - name: Créer le dépôt via l'API GitHub
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        curl -H "Authorization: token $GH_TOKEN" \
             -d "{\"name\": \"$repo_name\", \"auto_init\": true, \"private\": false}" \
             https://api.github.com/orgs/lumios-le-jeu/repos

    - name: Cloner le dépôt modèle et personnaliser la carte
      run: |
        git clone https://github.com/lumios-le-jeu/carte-a-gratter-template.git $repo_name
        cd $repo_name
        sed -i "s|PLACEHOLDER_IMAGE_URL|${{ github.event.inputs.background_image_url }}|g" index.html
        sed -i "s|PLACEHOLDER_TEXT|${{ github.event.inputs.scratch_text }}|g" index.html
        sed -i "s|PLACEHOLDER_COLOR|${{ github.event.inputs.color }}|g" index.html
        git add .
        git commit -m "Personnalisation de la carte avec le texte et l'image de fond"

    - name: Ajouter le dépôt distant et pousser
      run: |
        cd $repo_name
        git remote add origin "https://${{ secrets.GH_TOKEN }}@github.com/lumios-le-jeu/$repo_name.git"
        git push -u origin main

    - name: Activer GitHub Pages pour le nouveau dépôt
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        curl -X POST \
             -H "Authorization: token $GH_TOKEN" \
             -H "Accept: application/vnd.github.switcheroo-preview+json" \
             https://api.github.com/repos/lumios-le-jeu/$repo_name/pages/builds
