name: Génération de Carte à Gratter

on:
  workflow_dispatch:
    inputs:
      IMAGE_URL:
        description: "URL de l'image de fond pour la carte"
        required: true
        default: "https://github.com/lumios-le-jeu/cadeau/raw/main/bon.JPG"
      CARD_TEXT:
        description: "Texte à afficher sur la carte"
        required: true
        default: "Joyeux Anniversaire!"
      TEXT_COLOR:
        description: "Couleur du texte (hex)"
        required: true
        default: "#FF0000"

jobs:
  create_card:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Afficher les paramètres de création de carte
      run: |
        echo "Image URL: ${{ github.event.inputs.IMAGE_URL }}"
        echo "Texte de la carte: ${{ github.event.inputs.CARD_TEXT }}"
        echo "Couleur du texte: ${{ github.event.inputs.TEXT_COLOR }}"

    - name: Configurer Git User
      run: |
        git config --global user.email "etienneleborgne@gmail.com"
        git config --global user.name "lumios-le-jeu"

    - name: Créer un nouveau dépôt sur GitHub
      env:
        REPO_NAME: "card-$(date +%s)"
      run: |
        echo "Nom du dépôt : $REPO_NAME"
        git clone https://github.com/lumios-le-jeu/carte-a-gratter-template.git "$REPO_NAME"
        cd "$REPO_NAME"
        git remote rm origin
        git remote add origin "https://lumios-le-jeu:${{ secrets.GH_TOKEN }}@github.com/lumios-le-jeu/$REPO_NAME.git"
        git push -u origin main

    - name: Personnaliser la carte
      run: |
        cd "$REPO_NAME"
        sed -i "s|PLACEHOLDER_IMAGE_URL|${{ github.event.inputs.IMAGE_URL }}|g" index.html
        sed -i "s|PLACEHOLDER_TEXT|${{ github.event.inputs.CARD_TEXT }}|g" index.html
        sed -i "s|PLACEHOLDER_COLOR|${{ github.event.inputs.TEXT_COLOR }}|g" index.html
        git add .
        git commit -m "Personnalisation de la carte avec le texte et l'image de fond"
        git push -u origin main

    - name: Activer GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: "./$REPO_NAME"
